import type { Metadata } from 'next';
import { UserProfileClient } from '@/components/galaxy/UserProfileClient';
import { getUserStats } from '@/db/repositories/userRepository';

import { auth } from '@/lib/auth';

interface ProfilePageProps {
  params: {
    username: string;
  };
}

/**
 * Generates dynamic Open Graph and Twitter card metadata for each user's unique galaxy profile.
 */
export async function generateMetadata({
  params,
}: ProfilePageProps): Promise<Metadata> {
  const username = params.username;
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://commitcosmos.vercel.app';

  // Fetch stats to include real metrics in the dynamic OG image
  const stats = await getUserStats(username);
  const totalCommits = stats?.totalCommits ?? 0;
  const currentStreak = stats?.currentStreak ?? 0;

  // Dynamic Open Graph image generated by the Edge route
  const ogImageUrl = `${baseUrl}/api/og?username=${encodeURIComponent(
    username
  )}&totalCommits=${totalCommits}&currentStreak=${currentStreak}`;

  const title = `${username}'s galaxy`;
  const description = `Explore @${username}'s interactive 3D GitHub galaxy on CommitCosmos. ${totalCommits} stars ignited with a ${currentStreak}-day commit streak!`;

  return {
    title,
    description,
    openGraph: {
      title: `${username}'s galaxy | CommitCosmos`,
      description,
      url: `${baseUrl}/u/${encodeURIComponent(username)}`,
      siteName: 'CommitCosmos',
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: `${username}'s galaxy on CommitCosmos`,
        },
      ],
      type: 'profile',
    },
    twitter: {
      card: 'summary_large_image',
      title: `${username}'s galaxy | CommitCosmos`,
      description,
      images: [ogImageUrl],
      creator: `@${username}`,
    },
  };
}

export default async function UserProfilePage({ params }: ProfilePageProps) {
  const session = await auth();
  return (
    <UserProfileClient
      username={params.username}
      sessionUser={session?.user || null}
    />
  );
}
